### ISSUE TITLE
Does not work on server

### ISSUE THREAD

**Issue by Soham52** [Jummit/better-nether-map#1]
when a map is made in nether on a server, a corrupted map is made

to reproduce bug
1. install on server along with all the dependencies
2. join server
3. go to nether and make a map
4. a corrupted map is formed

![2021-07-06_14 25 01](https://user-images.githubusercontent.com/73898737/124572243-21cc4e00-de66-11eb-9329-06abbfe17bc0.png)

version: 1.17
mod version: 1.3.0

**Comment by Jummit** [comment]
Is the mod present on both the client and the server?

**Comment by Soham52** [comment]
> Is the mod present on both the client and the server?

Yes

**Comment by Jummit** [comment]
I reproduces the problem and am working on the issue right now.

**Comment by Jummit** [comment]
Fixed. Thanks for the bug report!
