### ISSUE TITLE
About 1.19.4 and 1.20 update

### ISSUE THREAD

**Issue by vico93** [Jummit/better-nether-map#10]
Is an update to these versions planned?

If not, can i ask on Fabric's Discord if someone is interested in porting themselves?

**Comment by Jummit** [comment]
> Is an update to these versions planned?
> 
> If not, can i ask on Fabric's Discord if someone is interested in porting themselves?

Maybe I'll get around to it, maybe not. If anyone is willing to open a PR, I'll happily accept it. The port itself should not be much more than changing the version number.
