### ISSUE TITLE
Maps Appears to Ignore Preference on Sampling Height

### ISSUE THREAD

**Issue by dagreenkat** [Jummit/better-nether-map#12]
Steps to reproduce: In config file, set useMapCreationHeight to false. Then set scanHeight to something other than 100. Create a map and observe that the produced map is sampling at y=100 despite your change.

**Comment by Jummit** [comment]
I checked, it's because the config entry is `minecraft:nether` when it should be [`minecraft:the_nether`](https://antifandom.com/minecraft/wiki/The_Nether#ID). You can fix the config right now, but I'll push a fixed version to Modrinth.

**Comment by Jummit** [comment]
Fixed and pushed to [Modrinth](https://modrinth.com/mod/better-nether-map/version/I0S6ufwt).
