### ISSUE TITLE
Update to 1.21 Please

### ISSUE THREAD

**Issue by sternschnaube** [Jummit/better-nether-map#16]

**Comment by Jummit** [comment]
Done: https://modrinth.com/mod/better-nether-map/version/4.0.0-1.21.1

**Comment by sternschnaube** [comment]
Thank you! 😄

**Comment by danieljross** [comment]
@Jummit Please update metadata such that the required Minecraft version is >= 1.21 instead of strictly 1.21.1. 1.21 is compatible in my testing.

**Comment by Jummit** [comment]
> @Jummit Please update metadata such that the required Minecraft version is >= 1.21 instead of strictly 1.21.1. 1.21 is compatible in my testing.

Done.
