### ISSUE TITLE
Issus with Spectrum

### ISSUE THREAD

**Issue by cosmicapiary** [Jummit/better-nether-map#17]
my understanding as to how this works is that it locks map rendering to y100 exactly. the problem is that Spectrum's cave dimension's y levels go from something like -400 to -65, taking place under the vanilla map. this means that any maps open in the cave dimension are unusable. is it possible for the y height to be on a per dimension basis? perhaps in a config? thanks ^^

**Comment by Jummit** [comment]
> my understanding as to how this works is that it locks map rendering to y100 exactly. the problem is that Spectrum's cave dimension's y levels go from something like -400 to -65, taking place under the vanilla map. this means that any maps open in the cave dimension are unusable. is it possible for the y height to be on a per dimension basis? perhaps in a config? thanks ^^

Per-dimension config is implemented, you can open the configuration from the mod menu.
