### ISSUE TITLE
Crash on server startup when used with ServerCore

### ISSUE THREAD

**Issue by SplendidAlakey** [Jummit/better-nether-map#2]
**MC** 1.17.1
**Fabric API** 0.40.8
**Better nether map** 1.5.0
**[ServerCore](https://modrinth.com/mod/servercore)** 1.2.1

When trying to use ServerCore together with Better nether map, the server crashes on startup. Initially opened the issue on ServerCore's github, [here](https://github.com/Wesley1808/ServerCore-Fabric/issues/2), thinking it was an incompatibility between ServerCore and Promenade, but the author discovered that it's actually Better nether map causing it: https://github.com/Wesley1808/ServerCore-Fabric/issues/2#issuecomment-945108164. Removing Better nether map lets the server launch just fine.

Log: [removed]

**Comment by Jummit** [comment]
Well, this was about to happen at some point. This mod relies on a large mixin override that breaks compatibility with anything that touches map logic. I'll try to take a look if I can fix it. I'll add ServerCore to the incompatible list for now. Thanks for the report!

**Comment by pahanakun** [comment]
I've opened up the latest JAR and changed the version requirements so it works with 1.18.1, just thought I'd let you know it still has an issue with the latest servercore version 1.2.6. Seems to work fine without it though, but I didn't actually make a map to test it.

**Comment by Jummit** [comment]
@pahanakun could you try if this issue is still present in version 2.0.0? I refactored the mixins to be much less intrusive.

**Comment by SplendidAlakey** [comment]
Just tried it on MC 1.18.2 with fabric API 0.47.10 and both the server and the client instantly crash. The server doesn't even have time to produce any logs before crashing, the client produced these logs:

Latest: https://gist.github.com/Footage2-Amply-Pounce/6f7abb335d7fef75864d034d218b6587

Crash: https://gist.github.com/Footage2-Amply-Pounce/5497528d7ef5ae23650cb858611f24bd

**Comment by Jummit** [comment]
Thanks for the quick test! It seems like the mixins don't work in the exported version. I'll look into it.

**Comment by Jummit** [comment]
I can't reproduce the error with just fabric API 0.47.10. Could you try to see if the error persists if you only use nethermap, fabric-api and cloth-config?

**Comment by SplendidAlakey** [comment]
The issue never happened with just Better nether map, it happens when Server core is also installed.

**Comment by Jummit** [comment]
I found the issue, push a new build right now.

**Comment by Jummit** [comment]
Could you try again with 2.0.1?

**Comment by SplendidAlakey** [comment]
Odd, now the client can start just fine with Server core + Better nether map, but the server shuts down claiming there's hard incompatibility with Server core: https://gist.github.com/Footage2-Amply-Pounce/b9a13091e5ebf2f7b84fdcbd8ffe9a2d

**Comment by Jummit** [comment]
Oh, I didn't remove the incompatibility from the mod.json :smile:
But it's a good sign that it's able to get to that point.

**Comment by Jummit** [comment]
2.0.2 pushed with fdc4ad6de604ac982c49f1467100a01d7896d91e

**Comment by SplendidAlakey** [comment]
Yep, now everything works. Thanks!

**Comment by Jummit** [comment]
> Yep, now everything works. Thanks!

Thank you for the testing and detailed logs!
