### ISSUE TITLE
1.18.1 please

### ISSUE THREAD

**Issue by ghost** [Jummit/better-nether-map#3]

**Comment by Aulluna** [comment]
How to upvote in github ?

**Comment by Jummit** [comment]
> How to upvote in github ?

There is a reaction system, click the smiley at the top right of the message.
Regarding the request for porting to the newer 1.18 versions, I don't have a Java development environment working right now, so sorry for the long wait. I'll try to get something going on the weekend.

**Comment by Jummit** [comment]
Fixed in a4fdbb11c87cb76512b1fa0a6825ef1732921db5
