### ISSUE TITLE
1.19.3 Update Please

### ISSUE THREAD

**Issue by Kluski42** [Jummit/better-nether-map#5]
Hey, my friends and I want to both update to the newest version and use this mod. Can we get a version of the mod for 1.19.3 please?

**Comment by Jummit** [comment]
In case I don't update it in time, I think you can lock the maps and use them for the time being. You can always add the mod after updating.

**Comment by sternschnaube** [comment]
Hello @Kluski42 and @Jummit, I was testing the mod right now - everything works fine on 1.19.3 😊
