### ISSUE TITLE
May I port to Forge 1.16?

### ISSUE THREAD

**Issue by Syrikal** [Jummit/better-nether-map#8]
Hi! Your project is licensed with the MIT license, so I could just go ahead, but I thought I'd ask just to be polite :)

Would you be OK with me porting this to Forge, for 1.16 initially and potentially for later versions as well? MIT license and full credit, of course.

**Comment by Jummit** [comment]
Sure, go ahead! The mod is not that complex, so I'm sure it shouldn't be hard. Tell me if you want we can share the [Modrinth project](https://modrinth.com/mod/better-nether-map) if you want to upload the jars.

**Comment by Syrikal** [comment]
Thanks! I've gotten it to mostly work (had to learn how to do mixins first) but I have the lingering issue that the direction of the player cursor doesn't update while in the nether. Do you have any idea why this is?

My code is at https://github.com/Syrikal/Nether-Map-Port.

Edit: wait, never mind. For some reason the nether map cursor spinning is linked to _time of day_, of all things, and I had /gamerule doDaylightCycle false.

I might try a mixin on MapData to disable that spinning.

**Comment by Syrikal** [comment]
It's done! I may have gone a little overboard. I'll upload it to CurseForge and let you know when it's available so you can put it on the modrinth.

**Comment by Syrikal** [comment]
https://www.curseforge.com/minecraft/mc-mods/better-nether-map-port

**Comment by Jummit** [comment]
I invited you to the Modrinth project, feel free to upload versions and edit the description to show the features available in the forge version. Please only change the TODO in the project description.

**Comment by Syrikal** [comment]
Sounds good! I'll do that as soon as I can.

**Comment by Jummit** [comment]
Closing this as the port is finished.
